### PR TITLE
Add Azure support to HypershiftDeployment

### PR DESCRIPTION
**Pull request by jnpacker**
* Includes new sample
* Changes to the CRD
* Split Provider infrastructure code into aws & azure. Sets the stage for more infrastructure support
* Modified tests for new split infrastructure layout

Signed-off-by: Joshua Packer <jpacker@redhat.com>

### CODE REVIEW

**Comment by jnpacker** [comment]
Something I did realize when adding this support, is that we probably want to replace the `default-resources.go` with `openshift/hypershift/.../examples.go`

**Comment by jnpacker** [comment]
There is still some work to make ManifestWork flow work with this as well.

**Comment by ianzhang366** [comment]
> Something I did realize when adding this support, is that we probably want to replace the default-resources.go with openshift/hypershift/.../examples.go

I will open an issue for this and we can work on it.

**Pull request merged**
