### PR TITLE
Update hypershift main

### PR DESCRIPTION
**Pull request by jnpacker**
# Build - Success
```script
[+] Building 158.5s (21/21) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                          0.0s
 => => transferring dockerfile: 38B                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                             0.0s
 => => transferring context: 35B                                                                                                                              0.0s
 => [internal] load metadata for registry.access.redhat.com/ubi8/ubi-minimal:latest                                                                           0.7s
 => [internal] load metadata for registry.ci.openshift.org/stolostron/builder:go1.17-linux                                                                    9.5s
 => [stage-1 1/2] FROM registry.access.redhat.com/ubi8/ubi-minimal:latest@sha256:eb98682661cc5fe83bbe583af9d55a90d698cfc0d14af5b83e4568c3e26b4516             5.4s
 => => resolve registry.access.redhat.com/ubi8/ubi-minimal:latest@sha256:eb98682661cc5fe83bbe583af9d55a90d698cfc0d14af5b83e4568c3e26b4516                     0.0s
 => => sha256:d7ae367da43804656e144ba093daff1a0b62b2388021c6f797aeb684cd5b6781 737B / 737B                                                                    0.0s
 => => sha256:1f84ae1fe524cfa9cbc46adada180bbdf3380f454b83416572331aa630ac1d3c 4.28kB / 4.28kB                                                                0.0s
 => => sha256:eb98682661cc5fe83bbe583af9d55a90d698cfc0d14af5b83e4568c3e26b4516 1.47kB / 1.47kB                                                                0.0s
 => => sha256:d3b9a4a690bf1791b874c3495c6a8e2c039150b5882374cd9c42dd4bba68ba31 39.63MB / 39.63MB                                                              3.4s
 => => sha256:a049ed70eeb87542c711449e14b6a7ccdde9ca2219d749fa0872aa755f2a89cb 1.73kB / 1.73kB                                                                3.7s
 => => extracting sha256:d3b9a4a690bf1791b874c3495c6a8e2c039150b5882374cd9c42dd4bba68ba31                                                                     1.7s
 => => extracting sha256:a049ed70eeb87542c711449e14b6a7ccdde9ca2219d749fa0872aa755f2a89cb                                                                     0.0s
 => [builder  1/13] FROM registry.ci.openshift.org/stolostron/builder:go1.17-linux@sha256:4a212967d5e0aeec0df2901db23d2d8f557d2de4be3adbd2eef3f5dea21c045c   52.3s
 => => resolve registry.ci.openshift.org/stolostron/builder:go1.17-linux@sha256:4a212967d5e0aeec0df2901db23d2d8f557d2de4be3adbd2eef3f5dea21c045c              0.0s
 => => sha256:38dd71adcfc1f964c6f3ba6ae3b6daa95f612681cfb05298b225bb6347942f56 1.79kB / 1.79kB                                                                0.5s
 => => sha256:ba9023aa6d4a1cd1e21cdf6e909404f90f9948097d9210cda1a5ea4669a0df6d 588.43MB / 588.43MB                                                           31.3s
 => => sha256:4a212967d5e0aeec0df2901db23d2d8f557d2de4be3adbd2eef3f5dea21c045c 756B / 756B                                                                    0.0s
 => => sha256:19bc53e0605b9606c9e314bdc716d2a60cbed896b3d694e8e76ccc21f84cae06 9.53kB / 9.53kB                                                                0.0s
 => => sha256:0a21bb5475ea5fbcfdeab2bbe08a1cf4ef0b55382d553d2c213620763078223c 81.44MB / 81.44MB                                                              4.3s
 => => extracting sha256:0a21bb5475ea5fbcfdeab2bbe08a1cf4ef0b55382d553d2c213620763078223c                                                                     4.3s
 => => extracting sha256:38dd71adcfc1f964c6f3ba6ae3b6daa95f612681cfb05298b225bb6347942f56                                                                     0.0s
 => => extracting sha256:ba9023aa6d4a1cd1e21cdf6e909404f90f9948097d9210cda1a5ea4669a0df6d                                                                    20.7s
 => [internal] load build context                                                                                                                             0.0s
 => => transferring context: 382.40kB                                                                                                                         0.0s
 => [builder  2/13] WORKDIR /go/src/github.com/stolostron/hypershift-deployment-controller                                                                    0.4s
 => [builder  3/13] COPY go.mod go.mod                                                                                                                        0.0s
 => [builder  4/13] COPY go.sum go.sum                                                                                                                        0.0s
 => [builder  5/13] RUN go mod download                                                                                                                      52.4s
 => [builder  6/13] COPY pkg/main.go pkg/main.go                                                                                                              0.0s
 => [builder  7/13] COPY api/ api/                                                                                                                            0.0s
 => [builder  8/13] COPY pkg/controllers/ pkg/controllers/                                                                                                    0.0s
 => [builder  9/13] COPY pkg/helper/ pkg/helper/                                                                                                              0.0s
 => [builder 10/13] COPY pkg/constant/ pkg/constant/                                                                                                          0.0s
 => [builder 11/13] COPY Makefile Makefile                                                                                                                    0.0s
 => [builder 12/13] COPY hack hack                                                                                                                            0.0s
 => [builder 13/13] RUN make build                                                                                                                           42.6s
 => [stage-1 2/2] COPY --from=builder /go/src/github.com/stolostron/hypershift-deployment-controller/bin/manager .                                            0.2s
 => exporting to image                                                                                                                                        0.3s
 => => exporting layers                                                                                                                                       0.3s
 => => writing image sha256:331abfd8d3719377256ab4cd38396d72e020bf3c14d1618bc4396a3e4b2499b2                                                                  0.0s
 => => naming to quay.io/jpacker/hypershift-deployment-controller:latest
```
# Testing API/Unit - Success
```script
coverage: 77.0% of statements
ok  	github.com/stolostron/hypershift-deployment-controller/pkg/controllers	7.255s	coverage: 77.0% of statements
```

# Issue reference
https://github.com/stolostron/backlog/issues/22096

### CODE REVIEW

**Comment by jnpacker** [comment]
/unhold 
The current plan is to continue to FF backplane-2.0 from main until we release backplane-2.1 at which point we stop FF of backplane-2.0 and start backplane-2.2, so at any given time we will be FF'ng two branches.

**Comment by mikeshng** [comment]
/unhold 

Previous /unhold didn't work maybe because it didn't have a newline after it.

**Pull request merged**
