### PR TITLE
Remove out dated Go module references

### PR DESCRIPTION
**Pull request by jnpacker**
Signed-off-by: Joshua Packer <jpacker@redhat.com>

* Now that AWS Static credential support is merged into hypershift, the go.mod replace of my fork can be removed from our vendoring.

### CODE REVIEW

**Comment by jnpacker** [comment]
Issue reference: https://github.com/stolostron/backlog/issues/19369

**Comment by jnpacker** [comment]
@ray-harris does this project need to be added to sonarcloud instance?

**Comment by ray-harris** [comment]
yes. done.

/test sonar

**Comment by ray-harris** [comment]
I created the project in Sonar, but it's failing with an error I haven't seen before. I'll look at it first thing in the morning.

**Comment by jnpacker** [comment]
No hurry. Maybe because the testsuite is a noop at this point as I'm still putting the repo together?

**Comment by ray-harris** [comment]
It's something with Sonar's settings. It never gets to a point where it's actually testing anything.

**Comment by ray-harris** [comment]
@jnpacker Fixed. It helps when I spell `management` correctly.

**Comment by jnpacker** [comment]
This is replaced by my latest patch

**Pull request closed without merging**
