### PR TITLE
Add security constraints to ensure the hosting cluster is a managed cluster and belongs to managedclusterset

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

# Description of the change(s):
* Added a new optional `validate-cluster-security` boolean flag to main binary. Default is false, but when enabled it will ensure a HypershiftDeployment CR has the right permission to work on a given hosting cluster.
* Added a client package for handling OCM foundation APIs lookups and helper functions call.
* Enhanced HypershiftDeployment reconcile to validate hosting cluster related security constraints (clusterSet, clusterSetBinding)
* Added helper functions for cluster security check.
* Automatically add the newly auto imported managed cluster to the same clusterSet as the hosting cluster.

## Why do we need this PR:
* Ensure a HypershiftDeployment CR has the right permission to work on a given hosting cluster if the `validate-cluster-security` param is enabled.

## Issue reference: 
* https://issues.redhat.com/browse/ACM-1261

## Test API/Unit - Success
```script
?   	github.com/stolostron/hypershift-deployment-controller/api/v1alpha1	[no test files]
?   	github.com/stolostron/hypershift-deployment-controller/pkg	[no test files]
ok  	github.com/stolostron/hypershift-deployment-controller/pkg/client	0.075s	coverage: 87.5% of statements
?   	github.com/stolostron/hypershift-deployment-controller/pkg/constant	[no test files]
ok  	github.com/stolostron/hypershift-deployment-controller/pkg/controllers	2.948s	coverage: 77.1% of statements
ok  	github.com/stolostron/hypershift-deployment-controller/pkg/controllers/autoimport	0.107s	coverage: 60.6% of statements
ok  	github.com/stolostron/hypershift-deployment-controller/pkg/helper	0.116s	coverage: 62.5% of statements
ok  	github.com/stolostron/hypershift-deployment-controller/test/integration	20.971s	coverage: [no statements]
```

### CODE REVIEW

**Comment by mikeshng** [comment]
/hold

Verifying with cluster lifecycle team regarding what to do when the hosting cluster belongs to multiple clusterSet then which clusterSet to pick for the newly created managedCluster. Will unhold when there is a decision.

**Comment by rokej** [comment]
@mikeshng Should we hold our review until you check with the ClusteLC team on multiple cluster sets?

**Comment by mikeshng** [comment]
> @mikeshng Should we hold our review until you check with the ClusteLC team on multiple cluster sets?

@rokej please go ahead and start reviewing the only line it impact is 
https://github.com/stolostron/hypershift-deployment-controller/pull/108/files#diff-d64828b88499eb84fd11bbf568a3b2a011bf0887c21af011db30cf2c1e7639efR216

```
mcv1beta1.ClusterSetLabel: helper.GetClusterSetName(managementCluster), // TODO handle multiple clusterSets
```
in `autoimport_controller.go`

/assign xiangjingli

**Comment by mikeshng** [comment]
> "clusterset can use arbitrary labels with the new API so it is not easy to do what you want (copy clusterSets from Y to X). You still can use the clusterset label if the clusterset is a legacy one"

There is no clean way of setting multiple clusterSet to a managedCluster according to cluster lifecycle team. The current implementation (setting the new managed cluster based on the hosting managed cluster's label) is the best we can do for now. 

/unhold

**Review by rokej — APPROVED** [review]

**Pull request merged**
